---
- name: Install Docker and Java on build-agent
  hosts: agent
  become: yes

  tasks:

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
